### ISSUE TITLE
naming question

### ISSUE THREAD

**Issue by scottromack** [tachyons-css/tachyons-verbose#1]
Would
.border-color--black { border-color: var(--black); }

make more sense than
.bordercolor-black { border-color: var(--black); }

??

gzip will compress repeated strings so there is no real size hit..
Just a thought...

**Comment by adrawerofthings** [comment]
Hey @ShaggyDude – can you say a little bit more about why? Am happy to reconsider.

My current rule of thumb for naming is `.PropertyNameInOneWord-ValueInOneWord-MediaQuery`

There are weird edge cases, but I find, for example, `.bordercolor-darkgrey` a bit easier to read/write than `.border-color-dark-grey`.

**Comment by scottromack** [comment]
I'm trying to get a 1 to 1 mapping of css as much as possible so

.border-color--black { border-color: black; } is more like a literal translation to me.
I have made a fork and am playing around with it to see if what I'm thinking makes sense..

**Comment by scottromack** [comment]
I am also trying to achieve readability over brevity because as stated before gzip loves long names..

**Comment by adrawerofthings** [comment]
Ahh gotcha – so like double dash corresponds to semicolon? Let m know what you think after experimenting with it! Would be curious/tempted for sure.

Was looking through my own examples, so I guess for me, this is more readable because it's a little more compact (yes I know it's ironic saying that for a verbose toolset):

`f5 fontstyle-italic fontweight-normal margintop-small black`
versus
`f5 font-style--italic font-weight--normal margin-top--small black`

What do you think?

**Comment by scottromack** [comment]
Just now coming back to this with fresh eyes. Yes, I think your way is better.

**Comment by adrawerofthings** [comment]
@ShaggyDude Thanks for coming back on this one. Good to know (as I occasionally wonder if I made the right choice in the first place)!
